import { spawnSync } from "node:child_process";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { createHash } from "node:crypto";
import path from "node:path";

const output = path.resolve(process.argv[2] ?? "release-artifacts");
await mkdir(output, { recursive: true });
function run(command, args) {
  const result = spawnSync(command, args, {
    encoding: "utf8",
    maxBuffer: 32 * 1024 * 1024,
  });
  if (result.error || result.status !== 0) {
    throw new Error(`${command} failed: ${result.error ?? result.stderr}`);
  }
  return result.stdout;
}
// npm_execpath is available when invoked with npm run; no shell interpolation.
if (!process.env.npm_execpath)
  throw new Error("Run via npm run sbom -- <output>");
const npmBom = JSON.parse(
  run(process.execPath, [
    process.env.npm_execpath,
    "sbom",
    "--sbom-format",
    "cyclonedx",
    "--package-lock-only",
  ]),
);
const before = await readFile("src-tauri/Cargo.lock");
const target = /host: (\S+)/.exec(run("rustc", ["-vV"]))?.[1];
if (!target) throw new Error("Cannot determine Rust target");
run("cargo", [
  "cyclonedx",
  "--manifest-path",
  "src-tauri/Cargo.toml",
  "--format",
  "json",
  "--spec-version",
  "1.5",
  "--target",
  target,
  "--all",
]);
if (!before.equals(await readFile("src-tauri/Cargo.lock")))
  throw new Error("SBOM generation changed Cargo.lock; review and rebuild");
const rustBom = JSON.parse(
  await readFile("src-tauri/chatplus-desktop.cdx.json", "utf8"),
);
// Local Cargo package IDs may contain build-machine paths. Replace consistently
// in component references and dependency edges, retaining unique opaque IDs.
function portable(value) {
  if (
    typeof value === "string" &&
    /(?:path\+file:|file:\/\/|(?:^|[?=&\s])[A-Za-z]:[\\/])/.test(value)
  ) {
    return `urn:chatplus:local:${createHash("sha256").update(value).digest("hex")}`;
  }
  if (Array.isArray(value)) return value.map(portable);
  if (value && typeof value === "object")
    return Object.fromEntries(
      Object.entries(value)
        .filter(
          ([key, item]) =>
            !(
              key === "purl" &&
              typeof item === "string" &&
              /(?:file:|(?:^|[?=&\s])[A-Za-z]:[\\/])/.test(item)
            ),
        )
        .map(([key, item]) => [key, portable(item)]),
    );
  return value;
}
for (const [name, bom] of [
  ["npm.cdx.json", npmBom],
  ["rust.cdx.json", rustBom],
]) {
  if (bom.bomFormat !== "CycloneDX" || !Array.isArray(bom.components))
    throw new Error("Invalid SBOM output");
  await writeFile(
    path.join(output, name),
    JSON.stringify(portable(bom), null, 2) + "\n",
  );
}
await writeFile(
  path.join(output, "SBOM-NOTES.txt"),
  `Dependency inventories generated by npm sbom and cargo-cyclonedx 0.5.9.\nRust target: ${target}; includes transitive and build dependencies.\nnpm includes development/build dependencies. These are not binary composition proofs.\nOS libraries and Microsoft WebView2 are not fully represented; inventory their installed versions separately.\nLocal path identifiers are replaced consistently by opaque SHA-256 URNs.\nThe first-party crate uses the repository's GPL-3.0-only LICENSE.\n`,
);
console.log(`Generated npm and Rust CycloneDX inventories for ${target}.`);
