#[derive(Clone, serde::Serialize, serde::Deserialize)]
pub struct BuildMetadata {
    pub semantic_version: String,
    pub display_version: String,
    pub build_date_utc: String,
    pub git_commit_full: Option<String>,
    pub git_commit_short: Option<String>,
    pub git_branch: Option<String>,
    pub git_tag: Option<String>,
    pub build_channel: String,
    pub is_dirty: Option<bool>,
    pub rust_version: Option<String>,
}
pub fn current() -> BuildMetadata {
    serde_json::from_str(include_str!(concat!(
        env!("OUT_DIR"),
        "/build-metadata.json"
    )))
    .expect("build metadata generated by build.rs")
}
#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn generated_metadata_is_additive_and_utc() {
        let build = current();
        assert_eq!(build.semantic_version, env!("CARGO_PKG_VERSION"));
        assert_eq!(build.build_date_utc.len(), 20);
        assert!(build.build_date_utc.ends_with('Z'));
        if let (Some(full), Some(short)) = (build.git_commit_full, build.git_commit_short) {
            assert!(full.starts_with(&short));
        }
    }
}
